// action constants

export const GET_CATEGORIES_DATA = "GET_CATEGORIES_DATA";
export const SET_DEFAULT_CATEGORY_ID = "SET_DEFAULT_CATEGORY_ID";
export const GET_CATEGORY_BASED_PROPERTY_TYPE = "GET_CATEGORY_BASED_PROPERTY_TYPE";
export const GET_PROPERTY_TYPES = "GET_PROPERTY_TYPES";


// types
