import { BASE_URL } from "../services/axiosInstance";

export const RESOURCE_BASE_URL = "https://resources.projects.datconsultancy.com/";
export const APPLICATION_RESOURCE_BASE_URL = "https://sandbox.projects.datconsultancy.com/resources/";
/** Protected Resource Base Url */
export const PROTECTED_RESOURCE_BASE_URL = Object.freeze(`${BASE_URL}resources/all/`);

export const enabledLanguages = [{ label: "English", iso: "en" }, { label: "Arabic", iso: "ar" }]
export const permissionSet = {
  role: {
    CREATE: "createRole",
    UPDATE: "updateRole",
    DELETE: "deleteRole",
    READ: "readRole",
  },
  areaUnit: {
    CREATE: "createAreaUnit",
    UPDATE: "updateAreaUnit",
    DELETE: "deleteAreaUnit",
    READ: "readAreaUnit",
  },
  currency: {
    CREATE: "createCurrency",
    UPDATE: "updateCurrency",
    DELETE: "deleteCurrency",
    READ: "readCurrency",
  },
  user: {
    CREATE: "createUser",
    UPDATE: "updateUser",
    DELETE: "deleteUser",
    READ: "readUser",
    ADD_USER_ROLE: "addUserRole",
  },
  country: {
    CREATE: "createCountry",
    UPDATE: "updateCountry",
    DELETE: "deleteCountry",
    READ: "readCountry",
  },
  systemModules: {
    CREATE: "createSystemModules",
    UPDATE: "updateSystemModules",
    DELETE: "deleteSystemModules",
    READ: "readSystemModules",
  },
  language: {
    CREATE: "createLanguage",
    UPDATE: "updateLanguage",
    DELETE: "deleteLanguage",
    READ: "readLanguage",
  },
  location: {
    CREATE: "createLocation",
    UPDATE: "updateLocation",
    DELETE: "deleteLocation",
    READ: "readLocation",
  },
  organization: {
    CREATE: "createOrganization",
    UPDATE: "updateOrganization",
    DELETE: "deleteOrganization",
    READ: "readOrganization",
  },
  permissions: {
    CREATE: "createPermissions",
    UPDATE: "updatePermissions",
    DELETE: "deletePermissions",
    READ: "readPermissions",
    GRANT: "grantPrivilegesToRole",
    VIEW_PERMISSIONS_LIST: "viewPermissonsList",
  },
  amenity: {
    CREATE: "createAmenity",
    UPDATE: "updateAmenity",
    DELETE: "deleteAmenity",
    READ: "readAmenity",
  },
  propertyType: {
    CREATE: "createPropertyType",
    UPDATE: "updatePropertyType",
    DELETE: "deletePropertyType",
    READ: "readPropertyType",
  },
  propertyPriceType: {
    CREATE: "createPropertyPriceType",
    UPDATE: "updatePropertyPriceType",
    DELETE: "deletePropertyPriceType",
    READ: "readPropertyPriceType",
  },
  propertyCategory: {
    CREATE: "createPropertyCategory",
    UPDATE: "updatePropertyCategory",
    DELETE: "deletePropertyCategory",
    READ: "readPropertyCategory",
  },
  property: {
    CREATE: "createProperty",
    UPDATE: "updateProperty",
    DELETE: "deleteProperty",
    READ: "readProperty",
  },
  propertyCategoryTypeAndPriceRelation: {
    CREATE: "createPropertyCategoryTypeAndPrice",
    UPDATE: "updatePropertyCategoryTypeAndPrice",
    DELETE: "deletePropertyCategoryTypeAndPrice",
    READ: "readPropertyCategoryTypeAndPrice",
  },
  propertyTypeAndAmenityRelation: {
    CREATE: "createPropertyTypeAndAmenityRelation",
    UPDATE: "updatePropertyTypeAndAmenityRelation",
    DELETE: "deletePropertyTypeAndAmenityRelation",
    READ: "readPropertyTypeAndAmenityRelation",
  },
  propertyTypeCategoryRelation: {
    CREATE: "createPropertyTypeCategoryRelation",
    UPDATE: "updatePropertyTypeCategoryRelation",
    DELETE: "deletePropertyTypeCategoryRelation",
    READ: "readPropertyTypeCategoryRelation",
  },
  sms: {
    CREATE: "createSMS",
    UPDATE: "updateSMS",
    DELETE: "deleteSMS",
    READ: "readSMS",
    MAKE_DEFAULT: "makeDefault",
  },
};

export const FRONT_END_URL = 'https://sandbox.yallahproperty.com'

export const monthFinder = [
  { id: 0, title: "Jan" },
  { id: 1, title: "Feb" },
  { id: 2, title: "Mar" },
  { id: 3, title: "Apr" },
  { id: 4, title: "May" },
  { id: 5, title: "Jun" },
  { id: 6, title: "Jul" },
  { id: 7, title: "Aug" },
  { id: 8, title: "Sep" },
  { id: 9, title: "Oct" },
  { id: 10, title: "Nov" },
  { id: 11, title: "Dec" },
];

export const NATIONALITIES = [
  "Afghan",
  "Albanian",
  "Algerian",
  "American",
  "Andorran",
  "Angolan",
  "Anguillan",
  "Antiguan and Barbudan",
  "Argentine",
  "Armenian",
  "Aruban",
  "Australian",
  "Austrian",
  "Azerbaijani",
  "Bahamian",
  "Bahraini",
  "Bangladeshi",
  "Barbadian",
  "Belarusian",
  "Belgian",
  "Belizean",
  "Beninese",
  "Bermudian",
  "Bhutanese",
  "Bolivian",
  "Bosnian and Herzegovinian",
  "Botswanan",
  "Brazilian",
  "British",
  "Bruneian",
  "Bulgarian",
  "Burkinese",
  "Burundian",
  "Cambodian",
  "Cameroonian",
  "Canadian",
  "Cape Verdean",
  "Caymanian",
  "Central African",
  "Chadian",
  "Chilean",
  "Chinese",
  "Colombian",
  "Comorian",
  "Congolese",
  "Cook Islander",
  "Costa Rican",
  "Croatian",
  "Cuban",
  "Curaçaoan",
  "Cypriot",
  "Czech",
  "Danish",
  "Djiboutian",
  "Dominican",
  "Dominican (Republic)",
  "Dutch",
  "East Timorese",
  "Ecuadorean",
  "Egyptian",
  "Emirati",
  "Equatorial Guinean",
  "Eritrean",
  "Estonian",
  "Eswatini",
  "Ethiopian",
  "Faroese",
  "Fijian",
  "Finnish",
  "French",
  "Gabonese",
  "Gambian",
  "Georgian",
  "German",
  "Ghanaian",
  "Gibraltarian",
  "Greek",
  "Grenadian",
  "Guatemalan",
  "Guernseyan",
  "Guinean",
  "Bissau-Guinean",
  "Guyanese",
  "Haitian",
  "Honduran",
  "Hong Konger",
  "Hungarian",
  "Icelandic",
  "Indian",
  "Indonesian",
  "Iranian",
  "Iraqi",
  "Irish",
  "Israeli",
  "Italian",
  "Ivorian",
  "Jamaican",
  "Japanese",
  "Jerseyite",
  "Jordanian",
  "Kazakh",
  "Kenyan",
  "Kiribati",
  "Kosovar",
  "Kuwaiti",
  "Kyrgyzstani",
  "Lao",
  "Latvian",
  "Lebanese",
  "Basotho",
  "Liberian",
  "Libyan",
  "Liechtenstein",
  "Lithuanian",
  "Luxembourger",
  "Macanese",
  "Macedonian",
  "Malagasy",
  "Malawian",
  "Malaysian",
  "Maldivian",
  "Malian",
  "Maltese",
  "Manx",
  "Marshallese",
  "Mauritanian",
  "Mauritian",
  "Mexican",
  "Micronesian",
  "Moldovan",
  "Monegasque",
  "Mongolian",
  "Montenegrin",
  "Montserratian",
  "Moroccan",
  "Mosotho",
  "Mozambican",
  "Myanmar (Burmese)",
  "Namibian",
  "Nauruan",
  "Nepalese",
  "New Zealander",
  "Nicaraguan",
  "Nigerien",
  "Nigerian",
  "Niuean",
  "North Korean",
  "Northern Irish",
  "Norwegian",
  "Omani",
  "Pakistani",
  "Palauan",
  "Palestinian",
  "Panamanian",
  "Papua New Guinean",
  "Paraguayan",
  "Peruvian",
  "Filipino",
  "Polish",
  "Portuguese",
  "Qatari",
  "Romanian",
  "Russian",
  "Rwandan",
  "Saint Lucian",
  "Salvadoran",
  "Samoan",
  "San Marinese",
  "Sao Tomean",
  "Saudi Arabian",
  "Scottish",
  "Senegalese",
  "Serbian",
  "Seychellois",
  "Sierra Leonean",
  "Singaporean",
  "Sint Maarten",
  "Slovak",
  "Slovenian",
  "Solomon Islander",
  "Somali",
  "South African",
  "South Korean",
  "South Sudanese",
  "Spanish",
  "Sri Lankan",
  "Sudanese",
  "Surinamer",
  "Swazi",
  "Swedish",
  "Swiss",
  "Syrian",
  "Taiwanese",
  "Tajik",
  "Tanzanian",
  "Thai",
  "Togolese",
  "Tongan",
  "Trinidadian or Tobagonian",
  "Tunisian",
  "Turkish",
  "Turkmen",
  "Turks and Caicos Islander",
  "Tuvaluan",
  "Ugandan",
  "Ukrainian",
  "Uruguayan",
  "Uzbekistani",
  "Vanuatuan",
  "Venezuelan",
  "Vietnamese",
  "Welsh",
  "Wallisian",
  "Yemenite",
  "Zambian",
  "Zimbabwean",
];

export const RELIGIONS = [
  "Adventism",
  "African Traditional Religions",
  "Agnosticism",
  "Atheism",
  "Bahá'í Faith",
  "Buddhism",
  "Cao Dai",
  "Cheondoism",
  "Christianity",
  "Confucianism",
  "Daoism",
  "Druze",
  "Hinduism",
  "Islam",
  "Jainism",
  "Judaism",
  "Non-Religious",
  "Paganism",
  "Pantheism",
  "Pastafarianism",
  "Rastafari",
  "Samaritanism",
  "Shinto",
  "Sikhism",
  "Spiritism",
  "Taoism",
  "Tenrikyo",
  "Unitarian Universalism",
  "Wicca",
  "Zoroastrianism",
]
