// action constants

export const SET_LOCATIONS_SEARCH_DATA = "SET_LOCATIONS_SEARCH_DATA";
export const SET_SELECTED_SEARCH_DATA = "SET_SELECTED_SEARCH_DATA";
export const SET_SELECTED_TREE_DATA = "SET_SELECTED_TREE_DATA";
export const SET_SELECTED_PATH_DATA = "SET_SELECTED_PATH_DATA";
export const SET_LOCATIONS_STATE_DATA = "SET_LOCATIONS_STATE_DATA";


// types
