// action constants

export const SET_ORGANIZATION_DATA = "SET_ORGANIZATION_DATA";
export const ADD_ORGANIZATION_DATA = "ADD_ORGANIZATION_DATA";
export const EDIT_ORGANIZATION_DATA = "EDIT_ORGANIZATION_DATA";
export const DELETE_ORGANIZATION_DATA = "DELETE_ORGANIZATION_DATA";
export const GET_SINGLE_ORGANIZATION_DATA = "GET_SINGLE_ORGANIZATION_DATA";
export const GET_ORGANIZATION_NUMBER = "GET_ORGANIZATION_NUMBER";

// types
