// action constants

export const SET_PROPERTIES_DATA = "SET_PROPERTIES_DATA";
export const ADD_PROPERTIES_DATA = "ADD_PROPERTIES_DATA";
export const EDIT_PROPERTIES_DATA = "EDIT_PROPERTIES_DATA";
export const DELETE_PROPERTIES_DATA = "DELETE_PROPERTIES_DATA";
export const GET_PROPERTY_DATA_BY_ID = "GET_PROPERTY_DATA_BY_ID";
export const GET_PROPERTIES_NUMBER = "GET_PROPERTIES_NUMBER";

// types
